/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddAircraftDialog: typeof import('./src/components/AddAircraftDialog.vue')['default']
    AircraftCard: typeof import('./src/components/AircraftCard.vue')['default']
    ChartWidget: typeof import('./src/components/dashboard/ChartWidget.vue')['default']
    ChatPanel: typeof import('./src/components/ChatPanel.vue')['default']
    ConfigForceGraph: typeof import('./src/components/ConfigForceGraph.vue')['default']
    CsvPreview: typeof import('./src/components/CsvPreview.vue')['default']
    DashboardContainer: typeof import('./src/components/dashboard/DashboardContainer.vue')['default']
    DataPanel: typeof import('./src/components/DataPanel.vue')['default']
    DataSourcePanel: typeof import('./src/components/dashboard/DataSourcePanel.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FlightParamRead: typeof import('./src/components/demo/FlightParamRead.vue')['default']
    GroundDiagnosis: typeof import('./src/components/demo/GroundDiagnosis.vue')['default']
    HealthTreeNode: typeof import('./src/components/demo/HealthTreeNode.vue')['default']
    InferingDialog: typeof import('./src/components/InferingDialog.vue')['default']
    MessageFeed: typeof import('./src/components/MessageFeed.vue')['default']
    PlaneSelector: typeof import('./src/components/demo/PlaneSelector.vue')['default']
    ProxyRuleEditor: typeof import('./src/components/ProxyRuleEditor.vue')['default']
    ProxyRuleForm: typeof import('./src/components/ProxyRuleForm.vue')['default']
    ReleaseSupport: typeof import('./src/components/demo/ReleaseSupport.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./src/components/SideNav.vue')['default']
    SortieDialog: typeof import('./src/components/SortieDialog.vue')['default']
    StealthHealth: typeof import('./src/components/demo/StealthHealth.vue')['default']
    TaskDialog: typeof import('./src/components/TaskDialog.vue')['default']
    TaskPanel: typeof import('./src/components/TaskPanel.vue')['default']
    TimeSeriesChart: typeof import('./src/components/demo/TimeSeriesChart.vue')['default']
    TrainingDialog: typeof import('./src/components/TrainingDialog.vue')['default']
    WorkspaceSidebar: typeof import('./src/components/WorkspaceSidebar.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
