/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddAircraftDialog: typeof import('./src/components/AddAircraftDialog.vue')['default']
    AircraftCard: typeof import('./src/components/AircraftCard.vue')['default']
    ChartWidget: typeof import('./src/components/dashboard/ChartWidget.vue')['default']
    ChatPanel: typeof import('./src/components/ChatPanel.vue')['default']
    CsvPreview: typeof import('./src/components/CsvPreview.vue')['default']
    DashboardContainer: typeof import('./src/components/dashboard/DashboardContainer.vue')['default']
    DataPanel: typeof import('./src/components/DataPanel.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    InferingDialog: typeof import('./src/components/InferingDialog.vue')['default']
    MessageFeed: typeof import('./src/components/MessageFeed.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNav: typeof import('./src/components/SideNav.vue')['default']
    TaskDialog: typeof import('./src/components/TaskDialog.vue')['default']
    TaskPanel: typeof import('./src/components/TaskPanel.vue')['default']
    TrainingDialog: typeof import('./src/components/TrainingDialog.vue')['default']
    WorkspaceSidebar: typeof import('./src/components/WorkspaceSidebar.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
